baseURL = "https://opensystemslab.com"
title = "Open Systems Lab"
languageCode = "en-us"
theme = "PaperMod"

[params]
  description = "Open Systems Lab - Kubernetes and Cloud Infrastructure Solutions"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowToc = true
  
  [params.homeInfoParams]
    Title = "Welcome to Open Systems Lab"
    Content = "Kubernetes and Cloud Infrastructure Solutions"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/OpenSystemsLab"

  [[params.socialIcons]]
    name = "website"
    url = "https://opensystemslab.com"
